language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

      #before_script:
      # - julia -e 'using Pkg; Pkg.add("FourierFlows");'

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'using Pkg; Pkg.test("FourierFlows", coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.dir("GeophysicalFlows"); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.dir("GeophysicalFlows"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

notifications:
  email: true
